name: Project Apollo push build

on: [push]

jobs:
    
  build:
    name: Build on Ubuntu 18.04 with dotnet 3.1.100
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build release with dotnet
      run: |
        dotnet restore --verbosity minimal
        dotnet build --configuration Release
